---
- name: install cinder packages
  yum: pkg={{ item }} state=present
  with_items:
    - iscsi-initiator-utils
    - openstack-cinder
    - openstack-utils
    - openstack-selinux
  tags: cinder

- name: deploy cinder config file
  template: src=cinder.conf.j2 dest=/etc/cinder/cinder.conf mode=0640 owner=root group=cinder
  notify: restart cinder
  tags: cinder

- name: run dbsync for cinder
  command: su -s /bin/sh -c '/usr/bin/cinder-manage db sync' cinder
  run_once: true
  tags: cinder

- name: disable cinder services in systemd
  service: name={{ item }} enabled=no
  with_items:
    - openstack-cinder-api
    - openstack-cinder-scheduler
    - openstack-cinder-volume
  tags: cinder

- name: create pacemaker resources for cinder-api
  pcs_resource: command=create name=cinder-api type=systemd:openstack-cinder-api clone=yes
  args:
    operations:
      - action: monitor
        options:
          start-delay: 10s
  run_once: true
  tags: cinder

- name: create pacemaker resources for cinder-volume
  pcs_resource: command=create name=cinder-volume type=systemd:openstack-cinder-volume clone=yes
  args:
    operations:
      - action: monitor
        options:
          start-delay: 10s
  run_once: true
  tags: cinder

- name: create pacemaker resources for cinder-scheduler
  pcs_resource: command=create name=cinder-scheduler type=systemd:openstack-cinder-scheduler clone=yes
  args:
    operations:
      - action: monitor
        options:
          start-delay: 10s
  run_once: true
  tags: cinder
