---
# This role deploys the mongod processes and sets up the replication set.

- name: install mongodb packages
  yum: pkg={{ item }} state=present
  with_items:
    - mongodb
    - mongodb-server
  tags: mongodb

- name: create the mongodb configuration file
  template: src=mongodb.conf.j2 dest=/etc/mongodb.conf
  notify: restart mongodb
  tags: mongodb

- name: generate the mongodb keyfile
  local_action: shell creates=special/mongodb-secret openssl rand -base64 741 > special/mongodb-secret
  tags: mongodb

- name: copy the keyfile for authentication
  copy: src=special/mongodb-secret dest=/var/lib/mongodb/secret owner=mongodb group=mongodb mode=0400
  tags: mongodb

- name: start the mongodb service
  service: name=mongod state=started
  tags: mongodb

- name: pause for a while
  wait_for: timeout=20
  tags: mongodb

- name: create the file to initialize the mongodb replica set
  template: src=repset_init.j2 dest=/tmp/repset_init.js
  tags: mongodb

- name: initialize the replication set
  command: /usr/bin/mongo --host {{ mongodb_bind_host }} --port "{{ mongodb_port | default(27017) }}" /tmp/repset_init.js 
  run_once: true
  tags: mongodb

- name: pause to allow primary election and sync of replica set
  wait_for: timeout=60
  tags: mongodb

- name: stop mongodb server
  service: name=mongod enabled=no state=stopped
  tags: mongodb

- name: create pacemaker resources for mongodb
  pcs_resource: command=create name=mongodb type=systemd:mongod clone=yes
  args:
    operations:
      - action: monitor
        options:
          start-delay: 10s
  run_once: true
  tags: mongodb
