---
- hosts: controller
  tasks:

  - name: delete pacemaker resource for galera
    command: pcs resource delete galera --force
    run_once: true
    ignore_errors: True
    tags:
        - mysql

  - name: stop local mariadb server
    service: name=mariadb state=stopped
    ignore_errors: True
    tags:
      - mysql

  - name: kill all mysql processes
    command: killall mysqld
    ignore_errors: True
    tags:
      - mysql

  - name: remove database and related packages
    yum: pkg={{ item }} state=absent
    ignore_errors: True
    with_items:
      - mariadb-galera-server
      - MySQL-python
      - xinetd
      - nfs-utils
    tags: 
      - mysql

  - name: remove mysql directory
    file: force=yes path=/var/lib/mysql/ state=absent
    ignore_errors: True
    tags: 
      - mysql

  - name: remove clustercheck config file
    file: force=yes path=/etc/sysconfig/clustercheck state=absent
    ignore_errors: True
    tags: 
      - mysql
