---

- name: install nova compute packages
  yum: pkg={{ item }} state=present
  with_items:
    - openstack-nova-compute
    - openstack-nova-network
    - openstack-utils
    - python-cinder
    - openstack-neutron-openvswitch
    - openstack-ceilometer-compute
    - ceph-common

- name: deploy nova config files
  template: src={{ item.src }} dest={{ item.dest }} mode=0640 owner=root group=nova
  notify: restart nova-compute
  with_items:
    - { src: nova.conf.j2, dest: /etc/nova/nova.conf }
    - { src: nova-api-paste.ini.j2, dest: /etc/nova/api-paste.ini }

- name: copy ceph.client.cinder.keyring to nova-compute nodes
  copy: src=special/ceph.client.cinder.keyring dest=/etc/ceph/ceph.client.cinder.keyring mode=0600 owner=root group=root

- name: deploy nova secret.xml file to enable access to the ceph storage
  template: src=nova-secret.xml.j2 dest=/tmp/secret.xml

- name: set libvirt secret value
  shell: virsh secret-set-value --secret $(virsh secret-define --file /tmp/secret.xml | awk '{print $2}') --base64 $(awk '/key/ {print $3}' /etc/ceph/ceph.client.cinder.keyring)

- name: start openstack-nova-compute services
  service: name={{ item }} enabled=yes state=started
  with_items:
    - libvirtd
    - openstack-nova-compute

- name: start openstack-nova-network
  service: name=openstack-nova-network enabled=yes state=started
