---
- name: flush db hosts
  command: mysqladmin flush-hosts

- name: restart keystone
  service: name=openstack-keystone state=restarted

- name: restart glance
  service: name={{ item }} state=restarted
  with_items:
    - openstack-glance-api
    - openstack-glance-registry

- name: restart nova
  service: name={{ item }} state=restarted
  with_items:
    - openstack-nova-api
    - openstack-nova-scheduler
    - openstack-nova-conductor
    - openstack-nova-consoleauth
    - openstack-nova-novncproxy

- name: restart neutron
  service: name={{ item }} state=restarted
  with_items:
    - neutron-server
    - neutron-l3-agent
    - neutron-dhcp-agent
    - neutron-metadata-agent
    - neutron-openvswitch-agent

- name: restart cinder
  service: name={{ item }} state=restarted
  with_items:
    - openstack-cinder-api
    - openstack-cinder-scheduler
    - openstack-cinder-volume

- name: restart horizon
  service: name={{ item }} state=restarted
  with_items:
    - openstack-nova-consoleauth
    - openstack-nova-novncproxy
    - httpd
    - memcached

- name: restart httpd
  service: name=httpd state=restarted

- name: reload kernel parameters
  command: sysctl -p

- name: restart haproxy
  service: name=haproxy state=restarted

- name: restart mariadb
  service: name=mariadb state=restarted

