---
- name: install cinder packages
  yum: pkg={{ item }} state=present
  with_items:
    - openstack-cinder
    - openstack-utils
    - openstack-selinux
  tags: cinder

- name: run db_sync for cinder
  shell: creates=/etc/cinder/db.synced su cinder -s /bin/sh -c '/usr/bin/cinder-manage db sync'; touch /etc/cinder/db.synced
  when: inventory_hostname == first_controller
  tags: cinder

- name: deploy cinder config file
  template: src=cinder.conf.j2 dest=/etc/cinder/cinder.conf mode=0640 owner=root group=cinder
  notify: restart cinder
  tags: cinder

- name: start cinder services
  service: name={{ item }} enabled=on state=started
  with_items:
    - openstack-cinder-api
    - openstack-cinder-scheduler
    - openstack-cinder-volume
  tags: cinder
