---
- name: install glance packages
  yum: pkg={{ item }} state=present
  with_items:
    - openstack-glance
    - openstack-utils
    - openstack-selinux
  tags: glance

- name: run db_sync for glance
  shell: creates=/etc/glance/db.synced su glance -s /bin/sh -c '/usr/bin/glance-manage db_sync'; touch /etc/glance/db.synced
  when: inventory_hostname == first_controller
  tags: glance

- name: deploy glance config files
  template: src={{ item.src }} dest={{ item.dest }} mode=0640 owner=root group=glance
  with_items:
    - { src: glance-registry.conf.j2, dest: /etc/glance/glance-registry.conf }
    - { src: glance-api.conf.j2, dest: /etc/glance/glance-api.conf }
  notify: restart glance
  tags: glance

- name: start glance services
  service: name={{ item }} enabled=on state=started
  with_items:
    - openstack-glance-registry
    - openstack-glance-api
  tags: glance
