---
- name: install haproxy
  yum: pkg=haproxy state=present
  tags: haproxy

- name: set sysctl parameters
  copy: src=haproxy-sysctl.conf dest=/etc/sysctl.d/haproxy.conf mode=0644 owner=root group=root
  notify: reload kernel parameters
  tags: haproxy

- name: set haproxy config file
  template: src=haproxy.cfg.j2 dest=/etc/haproxy/haproxy.cfg
  notify: restart haproxy
  tags: haproxy

- name: enable haproxy service
  service: name=haproxy enabled=yes state=started
  tags: haproxy

- name: push a script to create pacemaker resources for haproxy
  template: src=pcs-create-haproxy.j2 dest=/usr/local/sbin/pcs-create-haproxy.sh mode=0500
  when: inventory_hostname == first_controller
  tags: haproxy

- name: push a script to remove pacemaker resources for haproxy
  template: src=pcs-remove-haproxy.j2 dest=/usr/local/sbin/pcs-remove-haproxy.sh mode=0500
  when: inventory_hostname == first_controller
  tags: haproxy

- name: create pacemaker resources for haproxy
  command: /usr/local/sbin/pcs-create-haproxy.sh
  when: inventory_hostname == first_controller
  tags: haproxy

- name: remove pacemaker resources for haproxy
  command: /usr/local/sbin/pcs-remove-haproxy.sh
  when: inventory_hostname == first_controller
  tags: pcs-remove-haproxy
