---
- name: install horizon packages
  yum: pkg={{ item }} state=present
  with_items:
    - mod_wsgi
    - httpd
    - mod_ssl
    - python-memcached
    - openstack-dashboard
  tags: horizon

- name: deploy openstack-dashboard local settings
  template: src=dashboard-local_settings.j2 dest=/etc/openstack-dashboard/local_settings mode=0640 owner=root group=apache
  notify: restart horizon
  tags: horizon

- name: copy httpd server-status.conf
  copy: src=server-status.conf dest=/etc/httpd/conf.d/server-status.conf mode=0644
  notify: restart horizon
  tags: horizon

- name: listen on public ip address
  lineinfile: dest=/etc/httpd/conf/httpd.conf regexp="^Listen " insertafter="^#Listen " line="Listen {{ horizon_bind_host | default( primary_ipaddr ) }}:80"
  notify: restart httpd
  tags: horizon

- name: start httpd on the first controller
  service: name=httpd enabled=yes state=started
  tags: horizon

- name: get first http request
  get_url: url=http://{{ horizon_bind_host | default( primary_ipaddr ) }}/dashboard dest=/dev/null force=yes
  when: inventory_hostname == first_controller
  tags: horizon

- name: get a copy of the .secret_key_store file from the first controller
  fetch: src=/var/lib/openstack-dashboard/.secret_key_store dest=special/{{ first_controller }}-secret_key_store flat=yes
  when: inventory_hostname == first_controller
  tags: horizon

- name: distribute a copy of the .secret_key_store file
  copy: src=special/{{ first_controller }}-secret_key_store dest=/var/lib/openstack-dashboard/.secret_key_store mode=0600 owner=apache group=apache
  notify: restart horizon
  tags: horizon

