---
- name: install nova packages
  yum: pkg={{ item }} state=present
  with_items:
    - openstack-nova-console
    - openstack-nova-novncproxy
    - openstack-utils
    - openstack-nova-api
    - openstack-nova-conductor
    - openstack-nova-scheduler
    - python-cinderclient
    - python-memcached
  tags: nova

- name: run db sync for nova
  shell: creates=/etc/nova/db.synced su nova -s /bin/sh -c '/usr/bin/nova-manage db sync'; touch /etc/nova/db.synced
  when: inventory_hostname == first_controller
  tags: nova

- name: deploy nova config files
  template: src={{ item.src }} dest={{ item.dest }} mode=0640 owner=root group=nova
  notify: restart nova
  with_items:
    - { src: nova.conf.j2, dest: /etc/nova/nova.conf }
    - { src: nova-api-paste.ini.j2, dest: /etc/nova/api-paste.ini }
  tags: nova

- name: start nova services
  service: name={{ item }} enabled=on state=started
  with_items:
    - openstack-nova-consoleauth
    - openstack-nova-novncproxy
    - openstack-nova-api
    - openstack-nova-scheduler
    - openstack-nova-conductor
  tags: nova
