---
- name: install pacemaker packages
  yum: pkg={{ item }} state=present
  with_items:
    - pcs
    - fence-agents-all
  tags: pcs

- name: set password for the hacluster user
  user: name=hacluster password={{ pcs_cluster_pass_encoded }} update_password=always
  tags: pcs

- name: start pcsd
  service: name=pcsd enabled=yes state=started
  tags: pcs

- name: set pcs cluster auth
  command: pcs cluster auth -u hacluster -p {{ pcs_cluster_pass }} {{ controller_nodes | join(' ', attribute='name') }}
  tags: pcs

- name: start pacemaker cluster
  command: creates=/etc/corosync/corosync.conf pcs cluster setup --start --name {{ pcs_cluster_name }} {{ controller_nodes | join(' ', attribute='name') }}
  when: inventory_hostname == first_controller
  tags: pcs

- name: enable pacemaker service
  service: name=pacemaker enabled=yes state=started
  tags: pcs

- name: create stonith resources
  shell: pcs stonith show fence_{{ item.name }} || pcs stonith create fence_{{ item.name }} fence_{{ item.fencing.agent }} params login={{ item.fencing.login }} passwd="{{ item.fencing.passwd }}" action=reboot ipaddr={{ item.fencing.ipaddr }} lanplus="" verbose="" pcmk_host_list={{ item.name }}
  with_items: controller_nodes
  when: inventory_hostname == first_controller
  tags: pcs
