---
- name: install rabbitmq-server package
  yum: pkg=rabbitmq-server state=present
  tags: rabbitmq

- name: copy rabbitmq.config file
  copy: src=rabbitmq.config dest=/etc/rabbitmq/rabbitmq.config mode=0644 owner=root group=root
  tags: rabbitmq

- name: deploy rabbitmq-env.conf file
  template: src=rabbitmq-env.conf.j2 dest=/etc/rabbitmq/rabbitmq-env.conf mode=0644 owner=root group=root
  tags: rabbitmq

- name: generate erlang cookie file on the first controller
  command: creates=/var/lib/rabbitmq/.erlang.cookie systemctl start rabbitmq-server
  when: inventory_hostname == first_controller
  tags: rabbitmq

- name: fetch erlang cookie file from the first controller
  fetch: src=/var/lib/rabbitmq/.erlang.cookie dest=special/{{ first_controller }}-erlang.cookie flat=yes
  when: inventory_hostname == first_controller
  tags: rabbitmq

- name: distribute erlang cookie file to other controller nodes
  copy: src=special/{{ first_controller }}-erlang.cookie dest=/var/lib/rabbitmq/.erlang.cookie mode=0400 owner=rabbitmq group=rabbitmq
  tags: rabbitmq

- name: start rabbitmq servers
  service: name=rabbitmq-server enabled=no state=started
  tags: rabbitmq

- name: stop rabbitmq app on other controller nodes
  shell: creates=/etc/rabbitmq/step.stop_app rabbitmqctl stop_app; touch /etc/rabbitmq/step.stop_app
  when: inventory_hostname != first_controller
  tags: rabbitmq

- name: join rabbitmq cluster from other controller nodes
  shell: creates=/etc/rabbitmq/step.join_cluster rabbitmqctl join_cluster rabbit@{{ hostvars[first_controller].ansible_hostname }}; touch /etc/rabbitmq/step.join_cluster
  when: inventory_hostname != first_controller
  tags: rabbitmq

- name: wait for rabbitmq cluster nodes to join
  wait_for: timeout=5
  tags: rabbitmq

- name: start rabbitmq app on other controller nodes
  shell: creates=/etc/rabbitmq/step.start_app rabbitmqctl start_app; touch /etc/rabbitmq/step.start_app
  tags: rabbitmq

- name: wait for rabbitmq apps to start
  wait_for: timeout=5
  tags: rabbitmq

- name: copy script to set rabbitmq HA policy
  copy: src=rabbitmq-set_policy.sh dest=/usr/local/sbin/rabbitmq-set_policy.sh mode=0700 owner=root group=root
  tags: rabbitmq

- name: set rabbitmq HA policy
  command: /usr/local/sbin/rabbitmq-set_policy.sh
  tags: rabbitmq

- name: create pcs resources for rabbitmq
  shell: pcs resource show rabbitmq-server-clone || pcs resource create rabbitmq-server systemd:rabbitmq-server op monitor start-delay=20s --clone
  when: inventory_hostname == first_controller
  tags: rabbitmq

