---
- name: define first controller fact
  set_fact: first_controller={{ groups['controller'][0] }}
  tags: setfacts

- name: set fact about primary ip address
  set_fact: primary_ipaddr={{ hostvars[inventory_hostname][ "ansible_" + primary_if ].ipv4.address }}
  tags: setfacts

- name: set fact about private ip address
  set_fact: private_ipaddr={{ hostvars[inventory_hostname][ "ansible_" + private_if ].ipv4.address }}
  tags: setfacts
