---
# temporary assign vip addresses to one controller

- name: deploy a script to temporary add vip addresses
  template: src=add_vip_addresses.j2 dest=/tmp/add_vip_addresses mode=0755
  tags:
    - keystone
    - glance
    - cinder
    - nova
    - heat
    - ceilometer

- name: deploy a script to remove temporary assigned vip addresses
  template: src=del_vip_addresses.j2 dest=/tmp/del_vip_addresses mode=0755
  tags:
    - keystone
    - glance
    - cinder
    - nova
    - heat
    - ceilometer

- name: temporary assign vip addresses on the first controller
  command: /tmp/add_vip_addresses
  when: inventory_hostname == first_controller
  tags:
    - keystone
    - glance
    - cinder
    - nova
    - heat
    - ceilometer

