---
use_cinder: true
use_cinder_lvmiscsi_volume_driver: false
use_cinder_nfs_volume_driver: false
use_ceph: false
use_glusterfs: false
use_netapp: false
use_netapp_copyoffload: false

cinder_set_host: true
cinder_host: volume
cinder_lvmiscsi_volume_backend_name: LVM_iSCSI
cinder_nfs_volume_backend_name: Generic_NFS
cinder_ceph_volume_backend_name: RBD
cinder_glusterfs_volume_backend_name: GlusterFS
cinder_netapp_volume_backend_name: NetApp
cinder_osapi_volume_listen_port: 8776
cinder_osapi_volume_workers: 10
cinder_auth_strategy: keystone
cinder_nfs_shares_config: "/etc/cinder/nfs_exports"
cinder_nfs_sparsed_volumes: true
conder_glusterfs_shares_config: "/etc/cinder/glusterfs_shares"
cinder_glusterfs_sparsed_volumes: true
cinder_glusterfs_qcow2_volumes: false

netapp_storage_family: ontap_cluster
netapp_storage_protocol: nfs
netapp_copyoffload_tool_path: "/usr/local/bin/na_copyoffload_64"
